<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>jakarta4g-websocket-parent</artifactId>
        <groupId>org.treblereel.gwt.jakarta.websocket</groupId>
        <version>0.1</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>common</artifactId>
    <packaging>jar</packaging>

    <name>GWT/J2CL Jakarta WebSocket API</name>
    <description>Client-side Jakarta WebSocket runtime API for J2CL</description>

    <dependencies>
        <dependency>
            <groupId>org.treblereel.gwt.jakarta.websocket</groupId>
            <artifactId>annotations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.elemental2</groupId>
            <artifactId>elemental2-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.elemental2</groupId>
            <artifactId>elemental2-dom</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.jsinterop</groupId>
            <artifactId>base</artifactId>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.java</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
        </resources>
    </build>

</project>
