<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.treblereel.gwt.jakarta.websocket</groupId>
    <artifactId>annotations</artifactId>
    <version>0.1</version>
    <packaging>jar</packaging>

    <name>GWT/J2CL compatible Jakarta WebSocket annotations</name>
    <description>GWT/J2CL compatible Jakarta WebSocket client annotations</description>
    <url>https://github.com/jakartaee/websocket/</url>

    <scm>
        <connection>scm:git:git://github.com/treblereel/jakarta4g-websocket.git</connection>
        <developerConnection>scm:git:ssh://github.com/treblereel/jakarta4g-websocket.git</developerConnection>
        <url>https://github.com/treblereel/jakarta4g-websocket/tree/master</url>
        <tag>HEAD</tag>
    </scm>

    <licenses>
        <license>
            <name>EPL-2.0</name>
            <url>http://www.eclipse.org/legal/epl-2.0</url>
            <distribution>repo</distribution>
        </license>
        <license>
            <name>GPL-2.0 WITH Classpath-exception-2.0</name>
            <url>https://www.gnu.org/software/classpath/license.html</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <organization>
        <name>Treblereel</name>
        <url>https://github.com/treblereel</url>
    </organization>

    <developers>
        <developer>
            <id>treblereel</id>
            <name>Dmitrii Tikhomirov</name>
            <email>treblereel@icloud.com</email>
        </developer>
    </developers>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <maven.compiler.version>3.8.0</maven.compiler.version>
        <maven.source.version>3.2.1</maven.source.version>
        <maven.fmt.plugin>2.9</maven.fmt.plugin>
        <maven.license.plugin>3.0</maven.license.plugin>
        <maven.gpg.plugin>1.6</maven.gpg.plugin>
        <maven.javadoc.plugin>3.2.0</maven.javadoc.plugin>
        <maven.scm.provider.gitexe>1.9.5</maven.scm.provider.gitexe>
    </properties>

    <build>
        <resources>
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.java</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>${maven.source.version}</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <phase>package</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>release</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <version>${maven.javadoc.plugin}</version>
                        <configuration>
                            <failOnError>false</failOnError>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>${maven.gpg.plugin}</version>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <version>0.9.0</version>
                        <extensions>true</extensions>
                        <configuration>
                            <publishingServerId>central</publishingServerId>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>